INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Терапевт');
INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Хирург');
INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Невролог');
INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Офтальмолог');
INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Травмвматолог');
INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Дерматовенеролог');
INSERT INTO H_SPECIALITY VALUES(nextval('seq_spec'), 'Медсестра');
INSERT INTO H_SPECIALITY VALUES(nextval('seq_spec'), 'Интерн');
INSERT INTO H_Speciality VALUES(nextval('seq_spec'), 'Кардиолог');

INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Быков', 'Андрей', 'Евгеньевич', 1401);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Кисегач', 'Анастасия', 'Константиновна', 1401);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Купитман', 'Иван', 'Натанович', 1406);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Скрябина', 'Любовь', 'Михайловна', 1407);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Королева', 'Маргарита', 'Павловна', 1407);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Левин', 'Борис', 'Аркадьевич', 1404);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Черноус', 'Варвара', 'Николаевна', 1408);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Романенко', 'Глеб', 'Викторович', 1401);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Лобанов', 'Семен', 'Семенович', 1408);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Ричардс', 'Фил', NULL, 1406);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Ульянова', 'Полина', 'Сергеевна', 1408);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Корнеев', 'Максим', 'Леонидович', 1402);
INSERT INTO H_DOCTOR VALUES(nextval('seq_doc'), 'Калинина', 'Софья', 'Яковлевна', 1405);

INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Безенчук', 'Федор', 'Николаевич', 'г. Артемовск', '+375256788098');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Берлага', 'Михаил', 'Александрович','г. Южногорск', '+375331234579');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Грицацуева', 'Нина', 'Ивановна','г. Прокопьевск', '+375299089096');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Паниковский', 'Самюэль','Михайлович', 'г. Криворуков', '+375244777881');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Христофоров', 'Эрнест', 'Ричардович','г. Бердянск', '+375991456682');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Щукина', 'Элла', 'Аркадьевна','г. Урюпинск', '+375113451173');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Бендер', 'Остап', 'Ибрагимович','г. Черноморск', '+375000000000');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Балаганов', 'Александр', 'Николаевич', 'г. Черноморск', '+375444567799');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Корейко', 'Александр', 'Иванович','г. Урюпинск', '+375337777777');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_1'),'Козлевич','Адам', 'Казимирович', 'г. Верхнехолмск', '+375172061544');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Растопыркин ', 'Григорий', 'Феликсович','г. Урюпинск', '+375173076553');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Рукоблудов', 'Леонид', 'Ильич', 'г. Криворуков', '+375172061544' );
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Филинов', 'Василий', 'Денисович', 'г. Артемовск', '+375552347890');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Тугодумов', 'Василий', 'Федорович', 'г. Верхнехолмск', '+375297777777');
INSERT INTO H_PATIENT VALUES(nextval('SEQ_PATIENT_2'),'Заныкин', 'Андрей', 'Данилович', 'г. Артемовск', '+375172124689');

INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Консультация', 50.00);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Первичный осмотр', 15.30);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Рефлексотерапия', 185.60);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Физиолечение', 5.30);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Курс терапевтического лечения', 47.75);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Курс профилактического лечения', 300.00);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Ренгеноскопия', 10.00);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'ЭКГ', 0.85);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Компьютерная томография', 450.99);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'МРТ', 560.70);
INSERT INTO H_SERVICES VALUES(nextval('SEQ_SRV'), 'Анализ крови', 0.35);

INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 13, 116002, '2012-09-22', 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 21, 116003, '2012-09-22', 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 11, 216002, '2012-09-22', 150);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 20, 116006, '2013-09-22', 160);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 18, 216003, '2013-09-22', 120);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 11, 116007, '2014-09-22', 150);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 20, 216004, '2015-09-22', 160);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 14, 116008, '2019-09-22', 210);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 19, 216001, '2019-09-22', 170);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 21, 116003, '2019-09-22', 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), NULL, 216005, '2020-09-22', 170);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 18, 216002, '2021-09-22', 140);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 16, 116004, '2021-09-22', 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 18, NULL, '2022-09-22', 120);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), NULL, 216001, '2022-09-23', 210);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 22, 216007, '2022-09-26', 130);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 21, 116003, '2022-09-26', 110);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), NULL, 216001, '2022-09-27', 170);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 22, 116008, '2022-09-28', 130);
INSERT INTO H_VISIT (N_VISIT,ID_DOCTOR,ID_PATIENT,DATE_VISIT,CODE_SRV) VALUES (NEXTVAL('SEQ_VISIT'), 12, 116007, '2022-09-29', 200);
