CREATE OR REPLACE FUNCTION patient_discount(
last_name varchar default '',
card_num int default 0
)
RETURNS integer AS $$
SELECT (
CASE
WHEN SUM(price) < 50 THEN 3
WHEN SUM(price) BETWEEN 50 AND 100 THEN 10
WHEN SUM(price) BETWEEN 100 AND 200 THEN 20
WHEN SUM(price) BETWEEN 200 AND 400 THEN 30
WHEN SUM(price) > 400 THEN 40
END)
FROM H_VISIT
JOIN H_PATIENT HP on HP.N_CARD = H_VISIT.ID_PATIENT
JOIN H_SERVICES HS on H_VISIT.CODE_SRV = HS.CODE_SRV
WHERE ID_PATIENT = card_num OR UPPER(HP.SURNAME) = UPPER(last_name);
$$ LANGUAGE SQL;
